"""
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

def divisors(n):
    i = 1
    ds = 0
    while i <= int(n**0.5):
        if n % i == 0:
            ds += 1
        i += 1
    return 2*ds

t = 1
i = 1
while divisors(t) <= 500:
    i += 1
    t += i
print t
# note that this takes a fair bit of time to run, maybe 20-30 seconds
